apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
spec:
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      hostname: gitlab-domin-intern
      containers:
      - name: gitlab
        image: gitlab/gitlab-ee:latest
        volumeMounts:
        - name: gitlab-volume
          mountPath: /etc/gitlab
          subPath: config/
        - name: gitlab-volume
          mountPath: /var/log/gitlab
          subPath: logs/
        - name: gitlab-volume
          mountPath: /var/opt/gitlab
          subPath: data/
      volumes:
      - name: gitlab-volume
        persistentVolumeClaim:
          claimName: gitlab-volume-claim
          
---

apiVersion: v1
kind: Service
metadata:
  name: gitlab
spec:
  selector:
    app: gitlab
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
  - name: ssh
    port: 22
  type: LoadBalancer
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-volume-claim
spec:
  storageClassName: gitlab-volume
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
      
---
 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-volume
spec:
  storageClassName: gitlab-volume
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.180.100
    path: /nfs-storage/gitlab
